cursor                  #928374 # gruvbox:light-mode(gray)
cursor_text_color       #fbf1c7 # gruvbox:light-mode(bg)
foreground              #3c3836 # gruvbox:light-mode(fg)
background              #fbf1c7 # gruvbox:light-mode(bg)
selection_foreground    #928374 # gruvbox:light-mode(gray)
selection_background    #3c3836 # gruvbox:light-mode(fg)
url_color               #076678 # gruvbox:light-mode(blue)
visual_bell_color       #427b58 # gruvbox:light-mode(aqua)
bell_border_color       #427b58 # gruvbox:light-mode(aqua)
active_border_color     #8f3f71 # gruvbox:light-mode(purple)
inactive_border_color   #bdae93 # gruvbox:light-mode(fg3)
active_tab_foreground   #282828 # gruvbox:light-mode(fg0)
active_tab_background   #bdae93 # gruvbox:light-mode(fg3)
inactive_tab_foreground #7c6f64 # gruvbox:light-mode(gray)
inactive_tab_background #ebdbb2 # gruvbox:light-mode(bg1)
# black
color0                  #bdae93 # gruvbox:light-mode(fg3)
color8                  #a89984 # gruvbox:light-mode(fg4)
# red
color1                  #cc241d # gruvbox:light-mode(red)
color9                  #9d0006 # gruvbox:light-mode(red)
# green
color2                  #98971a # gruvbox:light-mode(green)
color10                 #79740e # gruvbox:light-mode(green)
# yellow
color3                  #d79921 # gruvbox:light-mode(yellow)
color11                 #b57614 # gruvbox:light-mode(yellow)
# blue
color4                  #458588 # gruvbox:light-mode(blue)
color12                 #076678 # gruvbox:light-mode(blue)
# purple
color5                  #b16286 # gruvbox:light-mode(purple)
color13                 #8f3f71 # gruvbox:light-mode(purple)
# aqua
color6                  #689d6a # gruvbox:light-mode(aqua)
color14                 #427b58 # gruvbox:light-mode(aqua)
# white
color7                  #7c6f64 # gruvbox:light-mode(gray)
color15                 #3c3836 # gruvbox:light-mode(fg)
