cursor                  #928374 # gruvbox-dark(gray)
cursor_text_color       #282828 # gruvbox-dark(bg)
foreground              #ebdbb2 # gruvbox-dark(fg)
background              #282828 # gruvbox-dark(bg)
selection_foreground    #928374 # gruvbox-dark(gray)
selection_background    #ebdbb2 # gruvbox-dark(fg)
url_color               #83a598 # gruvbox-dark(blue)
visual_bell_color       #8ec07c # gruvbox-dark(aqua)
bell_border_color       #8ec07c # gruvbox-dark(aqua)
active_border_color     #d3869b # gruvbox-dark(purple)
inactive_border_color   #665c54 # gruvbox-dark(bg4)
active_tab_foreground   #fbf1c7 # gruvbox-dark(fg0)
active_tab_background   #665c54 # gruvbox-dark(bg4)
inactive_tab_foreground #a89984 # gruvbox-dark(gray)
inactive_tab_background #3c3836 # gruvbox-dark(bg1)
# black
color0                  #665c54 # gruvbox-dark(bg4)
color8                  #7c6f64 # gruvbox-dark(bg4)
# red
color1                  #cc241d # gruvbox-dark(red)
color9                  #fb4934 # gruvbox-dark(red)
# green
color2                  #98971a # gruvbox-dark(green)
color10                 #b8bb26 # gruvbox-dark(green)
# yellow
color3                  #d79921 # gruvbox-dark(yellow)
color11                 #fabd2f # gruvbox-dark(yellow)
# blue
color4                  #458588 # gruvbox-dark(blue)
color12                 #83a598 # gruvbox-dark(blue)
# purple
color5                  #b16286 # gruvbox-dark(purple)
color13                 #d3869b # gruvbox-dark(purple)
# aqua
color6                  #689d6a # gruvbox-dark(aqua)
color14                 #8ec07c # gruvbox-dark(aqua)
# white
color7                  #a89984 # gruvbox-dark(gray)
color15                 #bdae93 # gruvbox-dark(fg3)
