cursor                  #928374 # gruvbox-light(gray)
cursor_text_color       #fbf1c7 # gruvbox-light(bg)
foreground              #3c3836 # gruvbox-light(fg)
background              #fbf1c7 # gruvbox-light(bg)
selection_foreground    #928374 # gruvbox-light(gray)
selection_background    #3c3836 # gruvbox-light(fg)
url_color               #076678 # gruvbox-light(blue)
visual_bell_color       #427b58 # gruvbox-light(aqua)
bell_border_color       #427b58 # gruvbox-light(aqua)
active_border_color     #8f3f71 # gruvbox-light(purple)
inactive_border_color   #bdae93 # gruvbox-light(fg3)
active_tab_foreground   #282828 # gruvbox-light(fg0)
active_tab_background   #bdae93 # gruvbox-light(fg3)
inactive_tab_foreground #7c6f64 # gruvbox-light(gray)
inactive_tab_background #ebdbb2 # gruvbox-light(bg1)
# black
color0                  #bdae93 # gruvbox-light(fg3)
color8                  #a89984 # gruvbox-light(fg4)
# red
color1                  #cc241d # gruvbox-light(red)
color9                  #9d0006 # gruvbox-light(red)
# green
color2                  #98971a # gruvbox-light(green)
color10                 #79740e # gruvbox-light(green)
# yellow
color3                  #d79921 # gruvbox-light(yellow)
color11                 #b57614 # gruvbox-light(yellow)
# blue
color4                  #458588 # gruvbox-light(blue)
color12                 #076678 # gruvbox-light(blue)
# purple
color5                  #b16286 # gruvbox-light(purple)
color13                 #8f3f71 # gruvbox-light(purple)
# aqua
color6                  #689d6a # gruvbox-light(aqua)
color14                 #427b58 # gruvbox-light(aqua)
# white
color7                  #7c6f64 # gruvbox-light(gray)
color15                 #3c3836 # gruvbox-light(fg)
