#   ██████╗ ████████╗████████╗███████╗██████╗
#  ██╔═══██╗╚══██╔══╝╚══██╔══╝██╔════╝██╔══██╗
#  ██║   ██║   ██║      ██║   █████╗  ██████╔╝█████╗
#  ██║   ██║   ██║      ██║   ██╔══╝  ██╔══██╗╚════╝
#  ╚██████╔╝   ██║      ██║   ███████╗██║  ██║
#   ╚═════╝    ╚═╝      ╚═╝   ╚══════╝╚═╝  ╚═╝
#  ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

# Terminal shell script launcher, written in rust
# Source Code: https://github.com/kuokuo123/otter-launcher

[general]
default_module = "app"
empty_module = "po"
exec_cmd = "zsh -c"
vi_mode = false
esc_to_abort = true
cheatsheet_entry = "?"
cheatsheet_viewer = "less -R; clear"
clear_screen_after_execution = false
loop_mode = false
# sometimes the otter runs too fast even before the terminal window is ready; this slows it down by milliseconds; useful when chafa image is skewed
delay_startup = 0

[interface]
header = """
 \u001B[34;1m  \u001B[0m$USER@$(printf $HOSTNAME)\u001B[0m$(printf '\u001B[999C\u001B[14D')\u001B[31m\u001B[0m $(mpstat | awk 'FNR ==4 {print $4}') \u001B[33m󰍛\u001B[0m $(free -h | awk 'FNR == 2 {print $3}' | sed 's/i//')
    """
# header_cmd = "chafa --scale max --stretch $HOME/wallpapers/platform.jpg"
header_cmd_trimmed_lines = 0
place_holder = "type & search"
suggestion_mode = "list"
separator = """
$( \
    text="    modules"; \
    printf "\u001B[0;90m$text \
    $(printf -v line '%*s' \"$(( COLUMNS - $(printf "$text" | wc -m) - 3 ))\" ''; printf '%s' \"${line// /─}\")" \
)"""
footer = ""
suggestion_lines = 4
list_prefix = "    "
selection_prefix = "  \u001B[31;1m▌ "
prefix_padding = 3
empty_module_message = ""
customized_list_order = false
indicator_with_arg_module = ""
indicator_no_arg_module = ""
prefix_color = "\u001B[33m"
description_color = "\u001B[39m"
place_holder_color = "\u001B[30m"
hint_color = "\u001B[30m"
move_interface_right = 0
move_interface_down = 0

[overlay]
overlay_cmd = ""
overlay_trimmed_lines = 0
overlay_height = 0
move_overlay_right = 0
move_overlay_down = 0

[[modules]]
description = "desktop programs"
prefix = "app"
cmd = """
desktop_file() {
find /usr/share/applications -name "*.desktop" 2>/dev/null
find /usr/local/share/applications -name "*.desktop" 2>/dev/null
find "$HOME/.local/share/applications" -name "*.desktop" 2>/dev/null
find /var/lib/flatpak/exports/share/applications -name "*.desktop" 2>/dev/null
find "$HOME/.local/share/flatpak/exports/share/applications" -name "*.desktop" 2>/dev/null
}
selected="$(desktop_file | awk -F/ '{name=$NF; sub(/\\.desktop$/, "", name); print name}' | sort -k1,1 | cut -f2- | fzf --info-command 'echo -e " desktop apps ($FZF_POS/$FZF_TOTAL_COUNT)"' --cycle --gutter " " --pointer " ▌" --color "bg+:-1,pointer:1,info:8,separator:8,scrollbar:0" --prompt '  ' -m -d / --with-nth -1 )"
[ -z "$selected" ] && exit
echo "$selected" | while read -r line ; do setsid -f gtk-launch "$(basename $line)"; done
"""

[[modules]]
description = "power menu (fzf)"
prefix = "po"
cmd = """
function power {
if [[ -n $1 ]]; then
case $1 in
"shutdown") systemctl poweroff ;;
"reboot") systemctl reboot ;;
"lock") hyprlock -q ;;
"logout") ( [[ -n "$NIRI_SOCKET" ]] && niri msg action quit -s ) || ( [[ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]] && hyprctl dispatch exit ) ;;
esac fi }
power $(echo -e 'shutdown\nreboot\nlock\nlogout' | fzf --info-command 'printf " power menu ($FZF_POS/$FZF_TOTAL_COUNT)"' --cycle --gutter " " --pointer " ▌" --color "bg+:-1,pointer:1,info:8,separator:8,scrollbar:0" --prompt '  ' | tail -1)
"""

[[modules]]
description = "run commands"
prefix = "sh"
cmd = """
$(printf $TERM | sed 's/xterm-//g') -e zsh -c "{}"
"""
with_argument = true
unbind_proc = true

[[modules]]
description = "open files (fzf)"
prefix = "fo"
cmd = """
find $HOME -type f -not -path '*/.cache/*' 2>/dev/null | fzf --info-command 'printf " files ($FZF_POS/$FZF_TOTAL_COUNT)"' --cycle --gutter ' ' --pointer ' ▌' --color 'bg+:-1,pointer:1,info:8,separator:8,scrollbar:0' --prompt '  ' | setsid -f xargs -r -I [] xdg-open '[]'
"""

# [[modules]]
# description = "open dirs (yazi)"
# prefix = "yz"
# cmd = """
# find $HOME -type d -not -path '*/.cache/*' 2>/dev/null | fzf --info-command 'printf " directories ($FZF_POS/$FZF_TOTAL_COUNT)"' --cycle --gutter ' ' --pointer ' ▌' --color 'bg+:-1,pointer:1,info:8,separator:8,scrollbar:0' --prompt '  ' | xargs -r -I [] setsid -f "$(echo $TERM | sed 's/xterm-//g')" -e yazi '[]'
# """
