[general]
import = [
  "theme.toml"
]

[font]
size = 12.0
builtin_box_drawing = true

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"

[window]
padding = { x = 12, y = 12 }
opacity = 1.0
