[colors.primary]
background = "#282828" # gruvbox:dark-mode(bg)
foreground = "#ebdbb2" # gruvbox:dark-mode(fg)

[colors.normal]
black   = "#282828" # gruvbox:dark-mode(bg)
red     = "#cc241d" # gruvbox:dark-mode(red)
green   = "#98971a" # gruvbox:dark-mode(green)
yellow  = "#d79921" # gruvbox:dark-mode(yellow)
blue    = "#458588" # gruvbox:dark-mode(blue)
magenta = "#b16286" # gruvbox:dark-mode(purple)
cyan    = "#689d6a" # gruvbox:dark-mode(aqua)
white   = "#a89984" # gruvbox:dark-mode(gray)

[colors.bright]
black   = "#928374" # gruvbox:dark-mode(gray)
red     = "#fb4934" # gruvbox:dark-mode(red)
green   = "#b8bb26" # gruvbox:dark-mode(green)
yellow  = "#fabd2f" # gruvbox:dark-mode(yellow)
blue    = "#83a598" # gruvbox:dark-mode(blue)
magenta = "#d3869b" # gruvbox:dark-mode(purple)
cyan    = "#8ec07c" # gruvbox:dark-mode(aqua)
white   = "#ebdbb2" # gruvbox:dark-mode(fg)
