[colors.primary]
background = "#282828" # gruvbox-dark(bg)
foreground = "#ebdbb2" # gruvbox-dark(fg)

[colors.normal]
black   = "#282828" # gruvbox-dark(bg)
red     = "#cc241d" # gruvbox-dark(red)
green   = "#98971a" # gruvbox-dark(green)
yellow  = "#d79921" # gruvbox-dark(yellow)
blue    = "#458588" # gruvbox-dark(blue)
magenta = "#b16286" # gruvbox-dark(purple)
cyan    = "#689d6a" # gruvbox-dark(aqua)
white   = "#a89984" # gruvbox-dark(gray)

[colors.bright]
black   = "#928374" # gruvbox-dark(gray)
red     = "#fb4934" # gruvbox-dark(red)
green   = "#b8bb26" # gruvbox-dark(green)
yellow  = "#fabd2f" # gruvbox-dark(yellow)
blue    = "#83a598" # gruvbox-dark(blue)
magenta = "#d3869b" # gruvbox-dark(purple)
cyan    = "#8ec07c" # gruvbox-dark(aqua)
white   = "#ebdbb2" # gruvbox-dark(fg)
